### ISSUE TITLE
Service Catalog walkthrough is broken for minikube

### ISSUE THREAD

**Issue by nilebox** [kubernetes-incubator/service-catalog#1069]
After introducing RBAC, Service Catalog walkthrough doesn't work for minikube anymore:
```
Error: release catalog failed: clusterroles.rbac.authorization.k8s.io "servicecatalog.k8s.io:apiserver" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["watch"]}] user=&{system:serviceaccount:kube-system:default ff1057e8-721b-11e7-b7bb-a23c9ee63bc7 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
while installing service catalog chart 
```
My understanding is that now there is a need for preconfiguring some roles in Kubernetes cluster before installing a Service Catalog helm chart.
It might be useful to add a script or separate documentation page describing this.

**Comment by nilebox** [comment]
@MHBauer can you help with this?
My current thinking is:
1. run `kubectl create clusterrolebinding fixDug --clsterrrole=cluster-admin --serviceaccount=kube-system:default`
2. take a look at the other steps in [local-up-cluster.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh) under `ENABLE_RBAC:true` option

**Comment by nilebox** [comment]
Possibly related https://github.com/kubernetes/minikube/issues/1734

**Comment by MHBauer** [comment]
Strugled with minikube for a while. No result.

Minikube needs to be started with `--extra-config=apiserver.Authorization.Mode=RBAC`.

Does everything work with `fixRBAC` binding created or are there more problems?

**Comment by jpeeler** [comment]
I'm getting the same result with both local-up-cluster and minikube. After enabling RBAC and making the default service account cluster-admin, I see an authentication prompt when executing `kubectl --context=service-catalog get brokers...` I'm not sure what I could be doing wrong, but I haven't ruled out user error yet.

**Comment by kibbles-n-bytes** [comment]
@jpeeler In order to get rid of that, I had to set a user/password combo for that context. So the full setup would look like the following:

```
kubectl config set-credentials service-catalog-creds --username=admin --password=admin
kubectl config set-cluster service-catalog-cluster --server="https://${API_SERVER_HOST}:443" --insecure-skip-tls-verify=true
kubectl config set-context service-catalog --cluster=service-catalog-cluster --user=service-catalog-creds
kubectl config use-context service-catalog
```

Maybe @MHBauer you can comment on whether that is a true solution, and whether we should add that to the walkthrough and why it works?

**Comment by kibbles-n-bytes** [comment]
Other than that, though, I believe the issue here was addressed in the walkthrough additions in #1076 . Is there more to be done for this @nilebox or are we good to close it?

**Comment by MHBauer** [comment]
Okay, I think I was confused. That's with rbac, but without aggregation. Probably with auth. I'm not sure if there's a default that might be getting accidentally exposed here. I definitely didn't set `admin:admin` credentials for anything intentionally.

**Comment by pmorie** [comment]
@MHBauer do you think this is fixed, then?

**Comment by MHBauer** [comment]
I need to check some things, but if the SA needs permissions because of the tiller pod for helm, then
```

**Comment by jpeeler** [comment]
I just tested with minikube again with RBAC enabled and I'm still getting prompted for credentials, but it works when adding them as described in https://github.com/kubernetes-incubator/service-catalog/issues/1069#issuecomment-319444019.

**Comment by MHBauer** [comment]
Okay, I didn't even think of the credentials, this sounds like a kubectl bug. As far as I know, we're not setting up credentials, and that user/pass has no effect other than getting you past a prompt.

**Comment by nilebox** [comment]
I can confirm that @kibbles-n-bytes's list of actions (preceded with `fixRBAC` actions mentioned by me above) worked for me.

> whether we should add that to the walkthrough and why it works?

@kibbles-n-bytes  Currently we don't have any guidance for `minikube` in our docs at all. Do we want to have one?

**Comment by kibbles-n-bytes** [comment]
@nilebox I meant more the credentials issue, which isn't unique to minikube. We have a section ([here](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/walkthrough.md#setting-up-a-new-kubectl-context)) that describes setting up the context, so I was thinking we could add the credentials setup there to get rid of the prompt until the issue is fixed.

However, I think also adding a mention of how to enable RBAC on minikube in the Troubleshooting section of the walkthrough would be good.

**Comment by arschles** [comment]
>However, I think also adding a mention of how to enable RBAC on minikube in the Troubleshooting section of the walkthrough would be good.

@kibbles-n-bytes I am partially addressing this in #1163, and will continue to do so in follow-ups. cc/ @jboyd01 who is also doing work in this arena

**Comment by arschles** [comment]
I've just changed docs for installing on Kube 1.7 (see [here](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/install-1.7.md)) to include the minikube startup command (see [here](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/install-1.7.md#rbac)), and install works properly. 

As such, I am closing this issue. 

Note that there is now a problem running the API server & controller, which I'll open a new issue for.
